name: Linux Build - QB

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install-pkgs:
    name: Build Entire Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update and Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake llvm python

      - name: Build Project
        run: |
          python3 build.py
